version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/interview_admin-main
hooks:  
AfterInstall:
  - location: scripts/change_permission.sh
      timeout: 300
      runas: root
  - location: scripts/installpkgs.sh
    timeout: 300
    runas: root
ApplicationStart:
  - location: scripts/appstart.sh
    timeout: 300
    runas: root
    
